Authorization _этап 1
Mobile-app-promotions-and-discounts/IOSApp pull request #124
Opened 2024-01-16 16:50 UTC by KudryashovAlexander

Всем привет!

Что сделано:
- Отредактирован экран входа
- Добавлены экраны регистрации и успешной регистрации
- Добавлен координатор для авторизации и регистрации
- настроена регистрация и авторизация

Поправлю в следующем спринте:
- Проверку вводимых значений почты и пароля (почта с "@", пароль сложный).

Локализация и восстановление пароля в будущих спринтах.

Есть еще идея объединить  LaunchViewController  и SplashViewController, у них функционал почти одинаковый. А экран приветствия добавить в LaunchScreen.

Возможно получилось много кода для одного ПР, ссори, по логике работы так получилось.
Посмотрите пожалуйста, с комбайном и координатором работал впервые, не судите строго))

2024-01-18 11:31 UTC, MickeyRU requested changes
Саша привет!

По коду все здорово, оставил небольшой коммент. Я не смог проверит UI и работоспособность - приложение попросту не запускается. Думаю стоит взять текущий Dev и его влить в твою ветку и внести фиксы.

Твоя идея про скрещивание воедино LaunchViewController и SplashViewController верная. LaunchViewController создавался для презентации/защиты и создавался именно отдельно, чтобы ничего не поломать и показывать его фиксированное время на экране. По сути так и будет но под капотом будет сразу проверка авторизации.

2024-01-18 12:10 UTC, KudryashovAlexander commented on DiscountsAndPromotionsApp/Configuration/Localization.swift
Это решение еще было до меня)
В локализации строк очень помог бы [SwiftGen](https://github.com/SwiftGen/SwiftGen), но он устанавливается через CocoaPods или HomeBrew, через SPM не устанавливается. 
Пользователь создает стринговые значения и он автоматом создает enum с нужным текстом.

2024-01-18 12:10 UTC, KudryashovAlexander commented on DiscountsAndPromotionsApp/Configuration/Localization.swift
> +        static let RegistrationErrorTitle = NSLocalizedString("RegistrationError", tableName: "RegistrationFlow", comment: "")
Ссори, упустил

2024-01-18 12:11 UTC, KudryashovAlexander commented on DiscountsAndPromotionsApp/Navigation/AuthCoordinator.swift
> +
Поправлю

2024-01-18 12:12 UTC, KudryashovAlexander commented on DiscountsAndPromotionsApp/Configuration/Localization.swift
> +        static let RegistrationErrorTitle = NSLocalizedString("RegistrationError", tableName: "RegistrationFlow", comment: "")
А почему конкретно не запускается, какие ошибки показываются?
<img width="280" alt="Снимок экрана 2024-01-18 в 15 11 51" src="https://github.com/Mobile-app-promotions-and-discounts/IOSApp/assets/42520208/f40c31a9-10ec-4ebb-90a6-1deac3bf0995">
Ветка dev влита в авторизацию.

2024-01-18 16:52 UTC, yakushef requested changes
Привет! Мне, к несчастью, тоже не удалось запустить приложение. На сплешскрине ловлю ошибку 401 "bad_authorization_header".

2024-01-18 16:57 UTC, yakushef commented on DiscountsAndPromotionsApp/Configuration/Localization.swift
> Хорошая идея держать все локализируемые строки в одном месте ссылкой на новую таблицу локализации. Возможно стоит дальше придерживаться всем такого подхода @yakushef, что скажешь?

Полностью поддерживаю. Тем более мне нужно будет привести в порядок локализацию на экране карточки товара. Я посмотрю что может SwiftGen, может нам действительно имеет смысл его подтянуть в проект

2024-01-19 07:38 UTC, KudryashovAlexander commented
Всем привет!

Нашел ошибку, из-за чего запрос на сервер отправлялся ранее, до проверки токена.
<img width="1090" alt="Снимок экрана 2024-01-19 в 10 34 43" src="https://github.com/Mobile-app-promotions-and-discounts/IOSApp/assets/42520208/3f2a43c8-f797-4b30-a790-d2c4f34232e7">
Запрос отправлялся с ProductNetworkService, пока что закомментировал строчку.
Попробуйте, плиз, запрос категорий вытащить из инициализации. Сам не стал править, так как с ним не работал, боюсь поломать.

2024-01-21 12:37 UTC, yakushef approved these changes
Теперь все работает 🫡
Я бы сначала влил текущий dev в main (потому что на последнем ревью наставник одобрил), а потом уже вливал бы этот и последующие наши ПР в dev.
Еще я доработал сервисы чтобы не было конфликтов с авторизацией, посмотри пожалуйста https://github.com/Mobile-app-promotions-and-discounts/IOSApp/pull/128

2024-01-21 19:00 UTC, MickeyRU commented
Все клево!)

2024-01-21 19:00 UTC, MickeyRU approved these changes
Все ок

2024-01-21 20:12 UTC, merged