Product card - Update UI + Transition to MVVM
Mobile-app-promotions-and-discounts/IOSApp pull request #94
Opened 2023-12-26 17:48 UTC by DanteIT94

2023-12-26 18:44 UTC, DanteIT94 commented
Из дева уже вмерджил изменения в свою ветку, теперь мерджу обратно в дев. Проблем с конфликтами нет
Из непонятного - у нас давно проблема с тем, что в коллекции открывается только 1 элемент (если несколько товаров - всегда открывается только 1 из массива, куда не кликни)

2023-12-27 18:54 UTC, yakushef commented
> Из дева уже вмерджил изменения в свою ветку, теперь мерджу обратно в дев. Проблем с конфликтами нет Из непонятного - у нас давно проблема с тем, что в коллекции открывается только 1 элемент (если несколько товаров - всегда открывается только 1 из массива, куда не кликни)?
> 
Привет! Проблема с одним элементом решится когда у нас будет сеть. Сейчас у всех наших моков одинаковый id.

2023-12-27 20:06 UTC, yakushef requested changes
Привет! Посмотрел твой код. Мне очень понравилось что ты явно глубже меня разобрался в комбайне! Изучил твои решения, потом причешу свой код, чтобы тоже использовать комбайн более полно, красиво и логично) А вот что касается дизайна - мне кажется что нужно еще раз внимательно сверить с макетом. Там есть несоответствия в шрифтах, цветах и прочем. Я оставил комментарии с предложением по навбару и с уточнением по верстке от дизайнеров.

Это один из самых больших и важных экранов, возможно чтобы успеть к презентации (учитывая что начинаются праздники) нам стоит перегруппироваться. Например, разделить доработки дизайна и логики, чтобы ими параллельно занимались два человека. Давай спишемся в общем чате и обсудим все вместе, как мы сможем эффективнее закончить с этим экраном в ближайшие пару недель?

2023-12-29 08:39 UTC, DanteIT94 commented on DiscountsAndPromotionsApp/UI/ProductCardScreen/ProductCardViewController.swift
> +        navigationController?.setNavigationBarHidden(galleryViewIsVisible, animated: true)
Исправил - там в статье конечно интересные моменты про новый кастомайз, но у нас проблема в проекте еще что есть КАСТОМНЫЙ розовый - а есть тот что в товаре - но сейчас вроде работает гораздо лучше)

2023-12-29 08:57 UTC, DanteIT94 commented on DiscountsAndPromotionsApp/UI/ProductCardScreen/Views/PriceInfoView.swift
> +        toFavoritesButton.setTitle("В избранное", for: .normal)
Поправил!

2023-12-29 09:18 UTC, DanteIT94 commented on DiscountsAndPromotionsApp/UI/ProductCardScreen/Views/PriceInfoView.swift
>      private func setupToFavoritesButton() {
Вроде поправил - но нужно больше покопаться в механике "Избранных"...

2023-12-30 18:29 UTC, yakushef commented on DiscountsAndPromotionsApp/UI/ProductCardScreen/Views/PriceInfoView.swift
> +        toFavoritesButton.setTitle("В избранное", for: .normal)
Давай попробуем ее отладить после того как я на днях залью рабочую сеть с получением товаров, сейчас еще мешает что у всех моков одинаковый ID возможно. Как вариант, стоит спросить у Паши - как автора системы избранного, лучше него никто не знает)

2024-01-07 19:00 UTC, closed without merging